version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    commands:
      - yarn
  build:
    commands:
      - yarn build
      - yarn test
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    name: build-$(date +%Y-%m-%d)
    base-directory: 'build'